### ISSUE TITLE
Creating proper alert message

### ISSUE THREAD

**Issue by lozinska** [KarlaChen/my-note#2]
Hello there! At the current moment when user press Save button popup message indicates that "Data saved!" even if there is no data has been entered. I would like to improve a little bit this part by adding message "No data to be saved!" when user did not entered any data but press button "Save". Please let me know if you would like to do this update. Thank you

**Comment by KarlaChen** [comment]
Sure, go a head.

**Comment by lozinska** [comment]
Thank you!
