### ISSUE TITLE
Pop up message is inconsistent with actual behavior

### ISSUE THREAD

**Issue by haichuan0424** [KarlaChen/my-note#4]
When the user leaves the message as part of the “Welcome to my notepad!” string, for example “Welcome to my" and tries to save the note, pop up message shows “No data to be saved”. However, if the page is reloaded, “Welcome to my” is displayed. 

Furthermore, it does not make sense to not let user save part of the “Welcome to my notepad!” string.

**Comment by KarlaChen** [comment]
Good point, Thanks to let me know and fix it for me.
